Tempura norm
simonsobs/so-lenspipe pull request #22
Opened 2020-12-10 21:47 UTC by qujia7

changed import from cmblensplus to pytempura.
Small change in the initial arguments in simple.py and removed args.curl redundant in solenspipe.py.

2020-12-13 23:19 UTC, msyriac requested changes

2020-12-13 23:19 UTC, msyriac commented on solenspipe/solenspipe.py
> +    import tempura as cs
Shouldn't this be pytempura?

2020-12-13 23:19 UTC, msyriac commented on solenspipe/solenspipe.py
> +    import tempura as cs
Similarly here and in several other places.

2020-12-14 09:06 UTC, NiallMac commented on solenspipe/solenspipe.py
> +    import tempura as cs
(Which is also imported at the top of the file, so does not need to be imported again anyway)

2020-12-14 09:07 UTC, qujia7 commented on solenspipe/solenspipe.py
> +    import tempura as cs
yes, I added previously the import on the top of the file but forgot to remove some of the previous imports. Those are removed now.

2020-12-14 13:27 UTC, msyriac commented
Thanks, merging soon. I'm guessing @NiallMac and @qujia7 have been able to install tempura successfully? It isn't a PyPI package yet, but should be able to do that soon.

2020-12-14 13:27 UTC, msyriac approved these changes

2020-12-14 14:32 UTC, merged