added fortran for n1 and python wrapper in solenspipe
simonsobs/so-lenspipe pull request #5
Opened 2019-11-18 20:20 UTC by qujia7

2019-11-18 21:30 UTC, msyriac requested changes
This looks great as a start! We may want to follow the example of simonsobs/pixell for wrapping in Fortran code to make this a bit more flexible. Let me know if you can look at that. Also looks like a lot of n1 derivative stuff is already here!

2019-11-21 00:27 UTC, msyriac commented on bin/Makefile
> +        FPY = f2py-2.7
We should not write any code that references anything related to Python 2.

2019-11-21 01:01 UTC, msyriac commented
I've added the fortran compiling to setup.py (the way that pixell does it). The Makefile is not needed anymore. One just needs to run e.g.:
python setup.py build_ext -i
or e.g.:
python setup.py build_ext -i --fcompiler=intelem --compiler=intelem

2019-11-21 21:10 UTC, ajvanengelen commented
This looks great so far - thanks!

2019-12-11 01:21 UTC, msyriac commented
@qujia7 can we modify this so that the fortran function passes back the result without having to save to disk? (Saving stuff with the same file name to disk is not thread-safe!)

2019-12-11 01:23 UTC, msyriac commented
Similarly, ideally, the lens potential and CMB spectra should be passed as arrays, not as filenames.

2020-03-11 14:10 UTC, msyriac commented
@qujia7 would be good to have the L_step as an argument too

2020-06-02 22:46 UTC, msyriac approved these changes

2020-06-02 22:47 UTC, merged